### PR TITLE
Added dependencies for new google plugins

### PR DESCRIPTION
**Pull request by this-Aditya**

### CODE REVIEW

**Comment by yatharthranjan** [comment]
Can you also add the relevant provider classes to RadarServiceImpl ?

**Comment by yatharthranjan** [comment]
Sorry just saw those were added in a separate PR. Can you just resolve the conflicts please?

**Comment by this-Aditya** [comment]
Done @yatharthranjan.

**Review by yatharthranjan — APPROVED** [review]
LGTM, thanks

**Pull request merged**
